site_name: TheRocketProject
site_url: https://therocketproject.com
theme:
  name: material
  logo: Logo.svg
  favicon: Logo.svg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: grey
      accent: blue grey
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: grey
      accent: blue grey

extra:
  alternate:
    - name: English
      link: /English/
      lang: en
    - name: Español
      link: /Español/
      lang: es