site_name: TheRocketProject
site_url: https://cdealbagtz.github.io/TheRocketProject/
theme:
  name: material
  logo: Logo.svg
  favicon: Logo.svg
  features:
    - navigation.sections
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: grey
      accent: blue grey
      media: "(prefers-color-scheme: dark)"
      
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: grey
      accent: blue grey
      media: "(prefers-color-scheme: light)"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format