/*
 * CommandInterface.h
 *
 *  Created on: 13 jun 2026
 *      Author: Chris
 */

#ifndef INC_TASKS_COMMANDINTERFACE_COMMANDINTERFACE_H_
#define INC_TASKS_COMMANDINTERFACE_COMMANDINTERFACE_H_



#endif /* INC_TASKS_COMMANDINTERFACE_COMMANDINTERFACE_H_ */
